





clean:
	rm -r -f cover
	rm -r -f contents
	rm -r -f list_of_figures
	rm -r -f list_of_tables
	rm -r -f */.out
	rm -f */*.dvi*
	rm -f */*.log*
	rm -f */*.tex*
	rm -f */words.out
	rm -f */spell.out
	rm -f */*.cpp_out*
	rm -f */*.ws_out*
	rm -f */bos.h


