

########################################################################


all:
	cd gen_poly_mask ; $(MAKE) $(PRINT_OPTS)
	cd plot_data_plane ; $(MAKE) $(PRINT_OPTS)
	cd plot_point_obs ; $(MAKE) $(PRINT_OPTS)
	cd ascii2nc ; $(MAKE) $(PRINT_OPTS)
	cd madis2nc ; $(MAKE) $(PRINT_OPTS)
	cd pb2nc ; $(MAKE) $(PRINT_OPTS)
	cd wwmca_tool ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	cd gen_poly_mask ; $(MAKE) $(PRINT_OPTS) clean
	cd plot_data_plane ; $(MAKE) $(PRINT_OPTS) clean
	cd plot_point_obs ; $(MAKE) $(PRINT_OPTS) clean
	cd ascii2nc ; $(MAKE) $(PRINT_OPTS) clean
	cd madis2nc ; $(MAKE) $(PRINT_OPTS) clean
	cd pb2nc ; $(MAKE) $(PRINT_OPTS) clean
	cd wwmca_tool ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


