name: tc_diag_driver_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - yapf
  - numpy
  - scipy
  - toml
  - pyyaml
  - matplotlib
  - pandas
  - pip
  - pygrib
  - xarray
  - netcdf4
  - pylint
  - rope
  - pip:
    - cira_dependencies/diag_lib-0.4.1.tar.gz
    - cira_dependencies/atcf_tools-0.12.0.tar.gz
