

########################################################################


all:
	@ echo
	@ cd basic      ; $(MAKE) $(PRINT_OPTS)
	@ cd libcode    ; $(MAKE) $(PRINT_OPTS)
	@ cd tools      ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	@ echo
	@ cd basic      ; $(MAKE) $(PRINT_OPTS) clean
	@ cd libcode    ; $(MAKE) $(PRINT_OPTS) clean
	@ cd tools      ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


