# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
# ** Copyright UCAR (c) 1992 - 2012
# ** University Corporation for Atmospheric Research (UCAR)
# ** National Center for Atmospheric Research (NCAR)
# ** Research Applications Lab (RAL)
# ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

########################################################################


all:
	@ echo
	@ cd basic      ; $(MAKE) $(PRINT_OPTS)
	@ cd libcode    ; $(MAKE) $(PRINT_OPTS)
	@ cd tools      ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	@ echo
	@ cd basic      ; $(MAKE) $(PRINT_OPTS) clean
	@ cd libcode    ; $(MAKE) $(PRINT_OPTS) clean
	@ cd tools      ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


gen_sources:
	@ echo
	@ cd basic      ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd libcode    ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd tools      ; $(MAKE) $(PRINT_OPTS) gen_sources


########################################################################

