
########################################################################


all:
	@ cd vx_grid              ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_nc_util           ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_data2d            ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_data2d_grib       ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_data2d_grib2      ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_data2d_nc_met     ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_data2d_nc_pinterp ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_data2d_factory    ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_gsl_prob          ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_gnomon            ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_nav               ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_pb_util           ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_afm               ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_ps                ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_color             ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_pxm               ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_render            ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_plot_util         ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_shapedata         ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_statistics        ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_stat_out          ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_analysis_util     ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	@ cd vx_grid              ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_nc_util           ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data2d            ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data2d_grib       ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data2d_grib2      ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data2d_nc_met     ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data2d_nc_pinterp ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data2d_factory    ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_gsl_prob          ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_gnomon            ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_nav               ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_pb_util           ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_afm               ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_ps                ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_color             ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_pxm               ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_plot_util         ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_render            ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_shapedata         ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_statistics        ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_stat_out          ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_analysis_util     ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


