

########################################################################


all:
	@ cd vx_data_grids    ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_grib_classes  ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_gdata         ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_contable      ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_met_util      ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_analysis_util ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_color         ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_gnomon        ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_gsl_prob      ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_nav           ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_afm           ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_ps            ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_pb_util       ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_plot_util     ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_pxm           ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_render        ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_wrfdata       ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_wrfmode       ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	@ cd vx_analysis_util ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_color         ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_contable      ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_data_grids    ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_gdata         ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_gnomon        ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_grib_classes  ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_gsl_prob      ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_met_util      ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_nav           ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_pb_util       ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_plot_util     ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_afm           ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_ps            ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_pxm           ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_render        ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_wrfdata       ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_wrfmode       ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


