

########################################################################


all:
	@ echo
	@ cd core       ; $(MAKE) $(PRINT_OPTS)
#	@ cd dev_utils  ; $(MAKE) $(PRINT_OPTS)
	@ cd other      ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	@ echo
	@ cd core       ; $(MAKE) $(PRINT_OPTS) clean
	@ cd dev_utils  ; $(MAKE) $(PRINT_OPTS) clean
	@ cd other      ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


