# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
# ** Copyright UCAR (c) 1992 - 2012
# ** University Corporation for Atmospheric Research (UCAR)
# ** National Center for Atmospheric Research (NCAR)
# ** Research Applications Lab (RAL)
# ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

########################################################################


all:
	@ echo
	@ cd vx_log         ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_cal         ; $(MAKE) $(PRINT_OPTS)
	@ cd enum_to_string ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_math        ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_util        ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_econfig     ; $(MAKE) $(PRINT_OPTS)
	@ cd vx_config      ; $(MAKE) $(PRINT_OPTS)


########################################################################


clean:
	@ echo
	@ cd vx_log         ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_cal         ; $(MAKE) $(PRINT_OPTS) clean
	@ cd enum_to_string ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_math        ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_util        ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_econfig     ; $(MAKE) $(PRINT_OPTS) clean
	@ cd vx_config      ; $(MAKE) $(PRINT_OPTS) clean


########################################################################


gen_sources:
	@ echo
	@ cd vx_log         ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd vx_cal         ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd enum_to_string ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd vx_math        ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd vx_util        ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd vx_econfig     ; $(MAKE) $(PRINT_OPTS) gen_sources
	@ cd vx_config      ; $(MAKE) $(PRINT_OPTS) gen_sources


########################################################################

