name: Compilation Options

# Test MET configuration/compilation options for all tags

on:

  # Note that scheduled cron events are run on the default branch.
  # Enable this schedule when main_v12.0 becomes the default branch.

  #  schedule:
  #  - cron: '0 7 * * 0''

  push:

    # NOTE: This branches entry is only for testing.
    #       Delete prior to merging into develop.
    branches:
      - bugfix_2760_develop_enable_python
    tags:
      - 'v**' 
    paths-ignore:
      - 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/labels/**'
      - '**/README.md'
      - '**/LICENSE.md'
      
  workflow_dispatch:

jobs:

  compile:
    name: Compile MET enable options
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config_opts:
          - ''
          - '--enable-all'
          - '--enable-grib2'
          - '--enable-python'
          - '--enable-ugrid'
          - '--enable-lidar2nc'
          - '--enable-mode_graphics'
          - '--enable-modis'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Create directories to store output
        run: mkdir -p ${RUNNER_WORKSPACE}/logs

      - name: Compile MET in Docker
        run: .github/jobs/build_docker_image.sh
        env:
          SOURCE_BRANCH: ${{ needs.job_control.outputs.branch_name }}
          MET_BASE_REPO: ${{ needs.job_control.outputs.met_base_repo }}
          MET_BASE_TAG: ${{ needs.job_control.outputs.met_base_tag }}
          MET_CONFIG_OPTS: ${{ matrix.config_opts }}

      - name: Copy all build log files into logs directory
        if: always()
        run: cp ${GITHUB_WORKSPACE}/*.log ${RUNNER_WORKSPACE}/logs/

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ${{ runner.workspace }}/logs
          if-no-files-found: ignore

