name: Build Docker Image and Trigger METplus Workflow

on:
  push:
    branches:
      - feature_1695_test_gha

jobs:

  trigger_metplus:
    name: Trigger METplus testing workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.METPLUS_BOT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dtcenter',
              repo: 'ghatest',
              workflow_id: 'external_trigger.yml',
              ref: 'test_external_trigger',
              inputs: {
                repo_name: '${{ github.repository }}',
                docker_tag: '${{ github.ref }}',
                actor: '${{ github.actor }}'
              },
            });

